server.port=0

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#this will ensure that the producer waits for the acknowledgment from
# all replicas before considering a message as sent successfully
#spring.kafka.producer.acks=all
